services:
  ollama:
    image: ollama/ollama:latest
    container_name: agribank-ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  app:
    build: .
    container_name: agribank-rag-app
    ports:
      - "8501:8501"
    environment:
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen3:0.6b
    depends_on:
      - ollama
    restart: always

volumes:
  ollama_data:
